/**
 * Content Store Rest Service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface FailedResponse { 
    code?: string;
    description?: string;
    errorReferenceNo?: string;
    messageType?: FailedResponse.MessageTypeEnum;
    requestGuid?: string;
    result?: boolean;
    /**
     * Unique GUID Reference of this Response
     */
    uniqueReference?: string;
}
export namespace FailedResponse {
    export type MessageTypeEnum = 'ERROR' | 'INFO' | 'SUCCESS';
    export const MessageTypeEnum = {
        ERROR: 'ERROR' as MessageTypeEnum,
        INFO: 'INFO' as MessageTypeEnum,
        SUCCESS: 'SUCCESS' as MessageTypeEnum
    };
}