CREATE SCHEMA Correspondence;

CREATE TABLE Correspondence.CorrespondenceHistory
( Id int generated by default as identity
, Agent varchar(255)
, TemplateStorageHandle varchar(255)
, Destination varchar(255)
, TmStamp timestamp
, Type varchar(255)
);

ALTER TABLE Correspondence.CorrespondenceHistory ALTER Id SET NOT NULL;
ALTER TABLE Correspondence.CorrespondenceHistory ALTER Agent SET NOT NULL;
ALTER TABLE Correspondence.CorrespondenceHistory ALTER TemplateStorageHandle SET NOT NULL;
ALTER TABLE Correspondence.CorrespondenceHistory ALTER Destination SET NOT NULL;
ALTER TABLE Correspondence.CorrespondenceHistory ALTER TmStamp SET NOT NULL;
ALTER TABLE Correspondence.CorrespondenceHistory ALTER Type SET NOT NULL;

ALTER TABLE Correspondence.CorrespondenceHistory
 ADD CONSTRAINT CorrespondenceHistory_PK PRIMARY KEY
  ( Id
  )
;

CREATE TABLE Correspondence.CorrespondenceTemplate
( Identifier varchar(255)
, CorrespondenceType varchar(100)
, SubjectHeading varchar(255)
, Template varchar(2000)
, Version integer
, IsLatest integer
, IsActive integer
);


ALTER TABLE Correspondence.CorrespondenceTemplate ALTER Identifier SET NOT NULL;
ALTER TABLE Correspondence.CorrespondenceTemplate ALTER CorrespondenceType SET NOT NULL;
ALTER TABLE Correspondence.CorrespondenceTemplate ALTER Template SET NOT NULL;
ALTER TABLE Correspondence.CorrespondenceTemplate ALTER Version SET NOT NULL;
ALTER TABLE Correspondence.CorrespondenceTemplate ALTER IsLatest SET NOT NULL;
ALTER TABLE Correspondence.CorrespondenceTemplate ALTER IsActive SET NOT NULL;

ALTER TABLE Correspondence.CorrespondenceTemplate
 ADD CONSTRAINT CORRESPONDENCETEMPLATE_PK PRIMARY KEY
  ( Identifier
  , Version
  )
;

CREATE TABLE Correspondence.CorrespondenceTemplateSnippets
( Identifier varchar(255)
, Template varchar(2000)
, CorrespondenceType varchar(255)
, IsLatest integer
, Version integer
);

ALTER TABLE Correspondence.CorrespondenceTemplateSnippets ALTER Identifier SET NOT NULL;
ALTER TABLE Correspondence.CorrespondenceTemplateSnippets ALTER Template SET NOT NULL;
ALTER TABLE Correspondence.CorrespondenceTemplateSnippets ALTER CorrespondenceType SET NOT NULL;
ALTER TABLE Correspondence.CorrespondenceTemplateSnippets ALTER IsLatest SET NOT NULL;
ALTER TABLE Correspondence.CorrespondenceTemplateSnippets ALTER Version SET NOT NULL;

ALTER TABLE Correspondence.CorrespondenceTemplateSnippets
 ADD CONSTRAINT CORRESPONDENCETEMPLATESNIPPETS_PK PRIMARY KEY
  ( Identifier
  , Version
  )
;
