CREATE TABLE CONTENTSTORE.CorrespondenceHistory
( Id int generated by default as identity
, Agent varchar(255)
, Template varchar(2000)
, Destination varchar(255)
, Date_sent timestamp
, Type varchar(255)
);

ALTER TABLE CONTENTSTORE.CorrespondenceHistory ALTER Id SET NOT NULL;
ALTER TABLE CONTENTSTORE.CorrespondenceHistory ALTER Agent SET NOT NULL;
ALTER TABLE CONTENTSTORE.CorrespondenceHistory ALTER Template SET NOT NULL;
ALTER TABLE CONTENTSTORE.CorrespondenceHistory ALTER Destination SET NOT NULL;
ALTER TABLE CONTENTSTORE.CorrespondenceHistory ALTER Date_sent SET NOT NULL;
ALTER TABLE CONTENTSTORE.CorrespondenceHistory ALTER Type SET NOT NULL;

ALTER TABLE CONTENTSTORE.CorrespondenceHistory
 ADD CONSTRAINT CORRESPONDENCEHISTORY_PK PRIMARY KEY
  ( Id
  )
;