ALTER TABLE CONTENTSTORE.CONTENTDATA ALTER COLUMN USRID TYPE VARCHAR(100) USING USRID::VARCHAR;
ALTER TABLE CONTENTSTORE.CONTENTLINK ALTER COLUMN USRID TYPE VARCHAR(100) USING USRID::VARCHAR;
ALTER TABLE CONTENTSTORE.CONTENTMETADATA ALTER COLUMN USRID TYPE VARCHAR(100) USING USRID::VARCHAR;
